use std::env;
use std::path::Path;

fn main() {
    // Self-check the vendored SHA-256 against FIPS known-answer vectors so a
    // broken hash implementation fails the build immediately (rather than
    // silently accepting a tampered download). Cheap — three small inputs.
    verify_sha256_selfcheck();

    // tauri-build validates that every path in `bundle.resources` exists and
    // tauri-codegen validates `frontendDist` when building without a dev URL
    // (plain `cargo build`/`cargo clippy`/`cargo test`). Both point at
    // gitignored `build/` subdirectories that don't exist on a fresh checkout:
    // `build/static` is populated by the native/asset steps below and
    // `build/render` is generated by Vite before bundling. Create them up
    // front so those cargo invocations work without a prior `yarn build:render`.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set");
    let project_dir = Path::new(&manifest_dir)
        .parent()
        .expect("manifest dir has a parent");
    for dir in ["static", "render"] {
        let dir = project_dir.join("build").join(dir);
        std::fs::create_dir_all(&dir)
            .unwrap_or_else(|e| panic!("failed to create {}: {e}", dir.display()));
    }

    tauri_build::build();

    // tauri-build only embeds the Windows application manifest (Common
    // Controls v6, needed for TaskDialogIndirect etc.) into the app binary
    // via `rustc-link-arg-bins`. Unit-test binaries are linked without it and
    // then fail to start with STATUS_ENTRYPOINT_NOT_FOUND (0xC0000139) on
    // systems where comctl32 v5 lacks those entry points.
    //
    // The manifest/icon/version resources are compiled by tauri-build into
    // `resource.lib` inside OUT_DIR; link the same resource into test
    // binaries so they carry the manifest too.
    if cfg!(target_os = "windows") && env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc") {
        let out_dir = env::var("OUT_DIR").expect("OUT_DIR is not set");
        // Some CMake invocations (e.g. the cli build) can drop a stub
        // `msvcrt.lib` (only a .drectve section) into OUT_DIR. If it ends up
        // on the linker search path it shadows the real CRT and breaks every
        // link with LNK2001 memcpy. Remove it defensively.
        let stray_msvcrt = std::path::Path::new(&out_dir).join("msvcrt.lib");
        if stray_msvcrt.exists() {
            let _ = std::fs::remove_file(&stray_msvcrt);
        }
        let resource = std::path::Path::new(&out_dir).join("resource.lib");
        if resource.exists() {
            // `rustc-link-arg-tests` covers integration-test binaries; the
            // lib unit-test harness (`ame_lib-<hash>.exe`) links the resource
            // itself via the `#[cfg(test)] #[link]` directive in lib.rs.
            println!("cargo:rustc-link-arg-tests={}", resource.display());
            println!("cargo:rustc-link-search=native={}", out_dir);
        } else {
            println!("cargo:warning=resource.lib not found in OUT_DIR; test binaries may lack the Common Controls v6 manifest");
        }
    }

    // Build and link the PP-OCR C++ FFI static library (always included).
    // Requires Visual Studio + CMake; a failure aborts the build rather than
    // producing a binary without OCR support.
    build_ppocr();

    // Build the JBeijing/DrEye helper CLIs (32-bit, bundled under
    // build/static/native/bin). A failure aborts the build.
    #[cfg(target_os = "windows")]
    build_cli();

    // Download runtime assets (Textractor, PP-OCR models) into build/static.
    if let Err(e) = download_runtime_deps() {
        // Hard-fail: the app would silently lack Textractor/PP-OCR at runtime.
        panic!("failed to download runtime dependencies: {e}");
    }
}

/// Download runtime assets into `<project>/build/static`.
///
/// The Rust backend consumes these at runtime via `paths::static_dir`:
/// TextractorCLI/texthook.dll for the Textractor extractor and ncnn models
/// for the PP-OCR engine. Downloads are idempotent (skipped when the files
/// already exist). A failure aborts the build so the app never runs with
/// missing runtime files.
fn download_runtime_deps() -> Result<(), String> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let static_dir = Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .join("build/static");
    let cache_dir = Path::new(&manifest_dir).join("target/runtime-deps");

    let textractor_files = [
        "textractor/x86/TextractorCLI.exe",
        "textractor/x86/texthook.dll",
        "textractor/x64/TextractorCLI.exe",
        "textractor/x64/texthook.dll",
    ];
    let ppocr_files = [
        "ppocr/PP-OCRv5_mobile_det.fp16.ncnn.param",
        "ppocr/PP-OCRv5_mobile_det.fp16.ncnn.bin",
        "ppocr/PP-OCRv5_mobile_rec.fp16.ncnn.param",
        "ppocr/PP-OCRv5_mobile_rec.fp16.ncnn.bin",
        "ppocr/PP-OCRv5_server_det.fp32.ncnn.param",
        "ppocr/PP-OCRv5_server_det.fp32.ncnn.bin",
        "ppocr/PP-OCRv5_server_rec.fp32.ncnn.param",
        "ppocr/PP-OCRv5_server_rec.fp32.ncnn.bin",
    ];

    if !all_exist(&static_dir, &textractor_files) {
        download_textractor(&static_dir, &cache_dir)?;
    }
    if !all_exist(&static_dir, &ppocr_files) {
        download_ppocr(&static_dir)?;
    }
    Ok(())
}

fn all_exist(base: &Path, files: &[&str]) -> bool {
    files.iter().all(|f| base.join(f).exists())
}

/// Compute the SHA-256 hex digest of a file using a small build-time-only
/// implementation (FIPS 180-4), so the build script can verify downloads
/// without pulling a crypto crate into build-dependencies.
fn sha256_hex(path: &Path) -> Result<String, String> {
    let data = std::fs::read(path).map_err(|e| e.to_string())?;
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let bitlen = (data.len() as u64) * 8;
    let mut msg = data;
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bitlen.to_be_bytes());
    for chunk in msg.chunks(64) {
        let mut w = [0u32; 64];
        for (i, c) in chunk.chunks(4).enumerate() {
            w[i] = u32::from_be_bytes([c[0], c[1], c[2], c[3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ (!e & g);
            let temp1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let temp2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(temp1);
            d = c;
            c = b;
            b = a;
            a = temp1.wrapping_add(temp2);
        }
        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
        h[5] = h[5].wrapping_add(f);
        h[6] = h[6].wrapping_add(g);
        h[7] = h[7].wrapping_add(hh);
    }
    Ok(h.iter().map(|x| format!("{x:08x}")).collect::<String>())
}

/// Verify a file's SHA-256 against an expected digest; error on mismatch.
fn verify_sha256(path: &Path, expected: &str) -> Result<(), String> {
    let actual = sha256_hex(path)?;
    if actual != expected {
        return Err(format!(
            "checksum mismatch for {}: expected {expected}, got {actual}",
            path.display()
        ));
    }
    Ok(())
}

/// Build-time self-check of the vendored SHA-256 against FIPS known-answer
/// vectors. Panics (failing the build) if the implementation is wrong.
fn verify_sha256_selfcheck() {
    let check = |input: &[u8], expected: &str| {
        // Hash the bytes via a temp file (sha256_hex operates on a file).
        let dir = std::env::temp_dir().join(format!("ame-build-sha-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("create sha selfcheck dir");
        let file = dir.join("vector.bin");
        std::fs::write(&file, input).expect("write sha selfcheck vector");
        let actual = sha256_hex(&file).expect("compute sha selfcheck");
        let _ = std::fs::remove_file(&file);
        assert_eq!(
            actual, expected,
            "vendored SHA-256 is broken (input {:?})",
            input
        );
    };
    check(
        b"",
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    );
    check(
        b"abc",
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
    );
    check(
        b"hello world",
        "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9",
    );
}

/// Download a file and verify its SHA-256 digest.
fn download_file_verified(url: &str, dst: &Path, expected_sha256: &str) -> Result<(), String> {
    download_file(url, dst)?;
    verify_sha256(dst, expected_sha256)
}

fn download_file(url: &str, dst: &Path) -> Result<(), String> {
    if dst.exists() {
        return Ok(());
    }
    // Info-level (shown only with `cargo build -v`).
    println!("downloading {url}");
    let result = (|| -> Result<(), String> {
        let resp = ureq::get(url).call().map_err(|e| e.to_string())?;
        let mut reader = resp.into_reader();
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        let mut file = std::fs::File::create(dst).map_err(|e| e.to_string())?;
        std::io::copy(&mut reader, &mut file).map_err(|e| e.to_string())?;
        Ok(())
    })();
    if result.is_err() {
        // Remove the partial file so the next build retries from scratch.
        let _ = std::fs::remove_file(dst);
    }
    result
}

fn download_textractor(static_dir: &Path, cache_dir: &Path) -> Result<(), String> {
    std::fs::create_dir_all(cache_dir).map_err(|e| e.to_string())?;
    let zip_path = cache_dir.join("Textractor-5.2.0-Zip-Version-English-Only.zip");
    let url = "https://github.com/Artikash/Textractor/releases/download/v5.2.0/Textractor-5.2.0-Zip-Version-English-Only.zip";
    if !zip_path.exists() {
        download_file(url, &zip_path)?;
    }

    let wanted = [
        (
            "Textractor/x86/TextractorCLI.exe",
            "textractor/x86/TextractorCLI.exe",
            "b8cebf066023db1ef5921135e0aa0f68f17bade795d910a2df58a3da2bebf233",
        ),
        (
            "Textractor/x86/texthook.dll",
            "textractor/x86/texthook.dll",
            "8fde589a24ef861c581b61829626d35d6b0fcc958aaaeca620dff630f1ed465b",
        ),
        (
            "Textractor/x64/TextractorCLI.exe",
            "textractor/x64/TextractorCLI.exe",
            "3c70e50a33fe1165e430eb3df6b9658c3a848257d294b92aab29d87632fe3783",
        ),
        (
            "Textractor/x64/texthook.dll",
            "textractor/x64/texthook.dll",
            "43b966f566e1d6362416041bfb55dc4e04aef7bcb8b5aae2da8179c24b2dd58e",
        ),
    ];
    let result = (|| -> Result<(), String> {
        let archive = std::fs::File::open(&zip_path).map_err(|e| e.to_string())?;
        let mut zip = zip::ZipArchive::new(archive).map_err(|e| e.to_string())?;
        for (entry_name, dst_rel, expected) in wanted {
            let dst = static_dir.join(dst_rel);
            if dst.exists() {
                continue;
            }
            let mut entry = zip
                .by_name(entry_name)
                .map_err(|e| format!("zip entry {entry_name}: {e}"))?;
            if let Some(parent) = dst.parent() {
                std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
            }
            let mut file = std::fs::File::create(&dst).map_err(|e| e.to_string())?;
            std::io::copy(&mut entry, &mut file).map_err(|e| e.to_string())?;
            verify_sha256(&dst, expected)?;
        }
        download_file_verified(
            "https://github.com/Artikash/Textractor/raw/master/LICENSE",
            &static_dir.join("textractor/LICENSE.Textractor.txt"),
            "8ceb4b9ee5adedde47b31e975c1d90c73ad27b6b165a1dcd80c7c545eb65b903",
        )
    })();
    if result.is_err() {
        // Drop the cached zip so a corrupt/partial download is retried.
        let _ = std::fs::remove_file(&zip_path);
    }
    result
}

fn download_ppocr(static_dir: &Path) -> Result<(), String> {
    const BASE: &str = "https://github.com/nzh63/ppocr2ncnn/releases/download/20250705";
    // SHA-256 digests of the pinned model files (verified on first download).
    let models = [
        (
            "PP-OCRv5_mobile_det.fp16.ncnn.param",
            "358f459680ae0e7a73e477469e529ce116f68c629019ec7a0b6457d2d9117934",
        ),
        (
            "PP-OCRv5_mobile_det.fp16.ncnn.bin",
            "857a96bc963725105b78a178dfcc3c0c3db1a7b9eef32244367b2cb105ccf60b",
        ),
        (
            "PP-OCRv5_mobile_rec.fp16.ncnn.param",
            "f52a6586ac3338d8c350db0c9f3c55ff2ecd3763327f9bc7f0efc091f8a63e74",
        ),
        (
            "PP-OCRv5_mobile_rec.fp16.ncnn.bin",
            "49d9907a55ba20fa6637f9f788f66ab00793bc8ce57a733a09dbe86b9a2e3db0",
        ),
        (
            "PP-OCRv5_server_det.fp32.ncnn.param",
            "ceef3c09aecf07c55547d646bbb3b86d63dddcf01b5c24ce40b4dc825b975741",
        ),
        (
            "PP-OCRv5_server_det.fp32.ncnn.bin",
            "adc576d9bacbaf38d9d1a275d3b216424607892246583cd4ef0f314cf71019f2",
        ),
        (
            "PP-OCRv5_server_rec.fp32.ncnn.param",
            "b3f747afafd6bc6bfbe379de32b6f06c6b7b67661397ef7d8f98d3b847c0ca18",
        ),
        (
            "PP-OCRv5_server_rec.fp32.ncnn.bin",
            "4578897bf70bf2ce0abb353f51f75fa6a5735f150e3b1a5ff1f5a3e30afa1778",
        ),
    ];
    for (model, expected) in models {
        download_file_verified(
            &format!("{BASE}/{model}"),
            &static_dir.join("ppocr").join(model),
            expected,
        )?;
    }
    download_file_verified(
        "https://github.com/PaddlePaddle/PaddleOCR/raw/refs/tags/v3.1.0/LICENSE",
        &static_dir.join("ppocr/LICENSE.ppocr.txt"),
        "3840c5c0c61c294264d2dd77b8777be6ddd90121ef4e0e64abcd22edea581d6e",
    )?;
    Ok(())
}

#[cfg(target_os = "windows")]
fn build_ppocr() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let ppocr_dir = std::path::Path::new(&manifest_dir).join("native/ppocr-ffi");
    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".into());
    let config_dir = if profile == "release" {
        "Release"
    } else {
        "Debug"
    };
    // Cargo's target dir: `CARGO_TARGET_DIR` when customized, otherwise
    // `<manifest_dir>/target` (NOT the repo root).
    let target_dir = env::var("CARGO_TARGET_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| std::path::Path::new(&manifest_dir).join("target"));

    // DLL 必须与被编译的应用同架构（进程内加载）。跟随 cargo 的目标架构：
    // x86_64 → x64，x86（i686-pc-windows-msvc，32 位构建）→ x86。ncnn 与
    // opencv-mobile 的预编译包两个架构都有，由 CMake 的 -DARCH 选择。
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_else(|_| "x86_64".into());
    let (cmake_arch, generator_platform) = match target_arch.as_str() {
        "x86" => ("x86", "Win32"),
        _ => ("x64", "x64"),
    };
    // 显式 `--target <triple>` 时产物在 <target>/<triple>/<profile>，否则
    // 在 <target>/<profile>`。按 OUT_DIR 判断本次调用的实际布局，避免把
    // 交叉构建的 DLL 覆盖到宿主布局（反之亦然）。
    let target_triple = env::var("TARGET").unwrap_or_default();
    let out_dir = env::var("OUT_DIR").unwrap_or_default();
    let uses_triple_layout = !target_triple.is_empty()
        && std::path::Path::new(&out_dir).starts_with(target_dir.join(&target_triple));
    let profile_dir = if uses_triple_layout {
        target_dir.join(&target_triple).join(&profile)
    } else {
        target_dir.join(&profile)
    };

    // Native sources are tracked so Cargo only re-runs this script when one
    // of them actually changes (otherwise `yarn dev` re-enters build.rs on
    // every invocation).
    let sources = walk_files(&ppocr_dir);
    track_files(&ppocr_dir);

    // The DLL is also distributed under build/static/native/bin (bundled into
    // packaged apps). When it already exists and is newer than every source
    // file, reuse it instead of re-running CMake — mirrors the old
    // `yarn build:native` incremental behavior.
    let static_bin = std::path::Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .join("build/static/native/bin");
    let canonical = static_bin.join("ppocr_ffi.dll");
    // 缓存戳记录已构建 DLL 的架构：先构建 x64 再构建 x86（或反过来）时，
    // 不能把另一架构的缓存 DLL 打包/复制给当前目标。
    let arch_stamp = static_bin.join("ppocr_ffi.dll.arch");
    let stamp_matches = std::fs::read_to_string(&arch_stamp)
        .map(|s| s.trim() == cmake_arch)
        .unwrap_or(false);
    let target_copies: Vec<std::path::PathBuf> = [
        profile_dir.join("ppocr_ffi.dll"),
        profile_dir.join("deps").join("ppocr_ffi.dll"),
    ]
    .to_vec();

    if !sources.is_empty()
        && stamp_matches
        && artifacts_fresh(&sources, std::slice::from_ref(&canonical))
    {
        // Cache hit: reuse the already-built DLL; just make sure the copies
        // next to the app/test binaries are still in place.
        for dest in target_copies {
            if let Some(parent) = dest.parent() {
                std::fs::create_dir_all(parent)
                    .unwrap_or_else(|e| panic!("failed to create {}: {e}", parent.display()));
            }
            if !dest.exists() {
                std::fs::copy(&canonical, &dest).unwrap_or_else(|e| {
                    panic!(
                        "failed to copy cached ppocr_ffi.dll to {}: {e}",
                        dest.display()
                    )
                });
            }
        }
        println!("using cached ppocr_ffi.dll ({cmake_arch}, PP-OCR engine)");
        return;
    }

    let dst = cmake::Config::new(&ppocr_dir)
        .define("CMAKE_INSTALL_PREFIX", "")
        .define("ARCH", cmake_arch)
        // VS 生成器的目标平台（相当于命令行 -A Win32/-A x64）；决定 MSVC
        // 工具集编出的 DLL 位数。
        .define("CMAKE_GENERATOR_PLATFORM", generator_platform)
        .build_target("ppocr_ffi")
        .build();

    // The DLL bundles ncnn + opencv; the Rust side loads it at runtime.
    let dll = dst.join("build").join(config_dir).join("ppocr_ffi.dll");
    if !dll.exists() {
        panic!(
            "ppocr_ffi.dll not found after CMake build: {}",
            dll.display()
        );
    }

    // Distribute the DLL next to the app binary (dev), next to the test
    // binaries, and into the bundled resources (packaged apps). static_bin
    // 只有一份（随包分发、与包架构一致）：先构建一种架构再构建另一种时
    // 会触发整体重建，属于预期代价。
    let mut dests = vec![
        profile_dir.clone(),
        profile_dir.join("deps"),
        static_bin.clone(),
    ];
    dests.dedup();
    for dest in dests {
        std::fs::create_dir_all(&dest)
            .unwrap_or_else(|e| panic!("failed to create {}: {e}", dest.display()));
        std::fs::copy(&dll, dest.join("ppocr_ffi.dll"))
            .unwrap_or_else(|e| panic!("failed to copy ppocr_ffi.dll to {}: {e}", dest.display()));
    }
    let _ = std::fs::write(&arch_stamp, cmake_arch);
    // Info-level (shown only with `cargo build -v`).
    println!("built ppocr_ffi.dll ({cmake_arch}, PP-OCR engine)");
}

#[cfg(not(target_os = "windows"))]
fn build_ppocr() {
    // PP-OCR native capture is Windows-only.
}

#[cfg(target_os = "windows")]
fn build_cli() {
    use std::process::Command;

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let cli_dir = std::path::Path::new(&manifest_dir).join("native/cli");
    // Dev layout: <project>/build/static/native/bin (packaged via
    // tauri.conf.json resources `../build/static/**/*` → `static/`).
    let bin_dir = std::path::Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .join("build/static/native/bin");
    let build_dir = std::path::Path::new(&manifest_dir).join("target/cli-build");

    // Same caching scheme as build_ppocr: skip CMake entirely when the CLIs
    // already exist and are newer than the sources.
    let sources = walk_files(&cli_dir);
    track_files(&cli_dir);
    let artifacts = [
        bin_dir.join("JBeijingCli.exe"),
        bin_dir.join("DrEyeCli.exe"),
    ];

    if !sources.is_empty() && artifacts_fresh(&sources, &artifacts) {
        println!("using cached JBeijingCli/DrEyeCli");
        return;
    }

    let build = || -> Result<(), String> {
        std::fs::create_dir_all(&build_dir).map_err(|e| e.to_string())?;

        let configure = Command::new("cmake")
            .args(["-G", "Visual Studio 17 2022", "-A", "Win32", "-S"])
            .arg(&cli_dir)
            .arg("-B")
            .arg(&build_dir)
            .status()
            .map_err(|e| format!("cmake configure failed: {e}"))?;
        if !configure.success() {
            return Err("cmake configure exited non-zero".into());
        }

        let compile = Command::new("cmake")
            .args(["--build"])
            .arg(&build_dir)
            .args(["--config", "Release", "--parallel"])
            .status()
            .map_err(|e| format!("cmake build failed: {e}"))?;
        if !compile.success() {
            return Err("cmake build exited non-zero".into());
        }

        std::fs::create_dir_all(&bin_dir).map_err(|e| e.to_string())?;
        for target in ["JBeijingCli.exe", "DrEyeCli.exe"] {
            let src = build_dir.join("Release").join(target);
            if !src.exists() {
                return Err(format!("{target} not found after CMake build"));
            }
            std::fs::copy(&src, bin_dir.join(target)).map_err(|e| e.to_string())?;
        }
        Ok(())
    };

    if let Err(e) = build() {
        panic!("failed to build JBeijing/DrEye CLIs: {e}");
    }
    // Info-level (shown only with `cargo build -v`).
    println!("built JBeijingCli/DrEyeCli into {}", bin_dir.display());
}

/// Recursively collect files under `dir` (used for freshness checks).
fn walk_files(dir: &Path) -> Vec<std::path::PathBuf> {
    let mut files = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                files.extend(walk_files(&path));
            } else {
                files.push(path);
            }
        }
    }
    files
}

/// Emit `cargo:rerun-if-changed` for every native source file so Cargo does
/// not re-run this build script unless the C++ sources actually change.
fn track_files(dir: &Path) {
    for file in walk_files(dir) {
        println!("cargo:rerun-if-changed={}", file.display());
    }
}

/// True when every artifact exists and is at least as new as the newest source.
fn artifacts_fresh(sources: &[std::path::PathBuf], artifacts: &[std::path::PathBuf]) -> bool {
    let newest = sources
        .iter()
        .filter_map(|f| std::fs::metadata(f).ok())
        .filter_map(|m| m.modified().ok())
        .max();
    let Some(newest) = newest else {
        return artifacts.iter().all(|a| a.exists());
    };
    artifacts.iter().all(|a| {
        std::fs::metadata(a)
            .ok()
            .and_then(|m| m.modified().ok())
            .map(|t| t >= newest)
            .unwrap_or(false)
    })
}
