use std::env;
use std::path::Path;

fn main() {
    // tauri-build validates that every path in `bundle.resources` exists and
    // tauri-codegen validates `frontendDist` when building without a dev URL
    // (plain `cargo build`/`cargo clippy`/`cargo test`). Both point at
    // gitignored `build/` subdirectories that don't exist on a fresh checkout:
    // `build/static` is populated by the native/asset steps below and
    // `build/render` is generated by Vite before bundling. Create them up
    // front so those cargo invocations work without a prior `yarn build:render`.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set");
    let project_dir = Path::new(&manifest_dir)
        .parent()
        .expect("manifest dir has a parent");
    for dir in ["static", "render"] {
        let dir = project_dir.join("build").join(dir);
        std::fs::create_dir_all(&dir)
            .unwrap_or_else(|e| panic!("failed to create {}: {e}", dir.display()));
    }

    tauri_build::build();

    // tauri-build only embeds the Windows application manifest (Common
    // Controls v6, needed for TaskDialogIndirect etc.) into the app binary
    // via `rustc-link-arg-bins`. Unit-test binaries are linked without it and
    // then fail to start with STATUS_ENTRYPOINT_NOT_FOUND (0xC0000139) on
    // systems where comctl32 v5 lacks those entry points.
    //
    // The manifest/icon/version resources are compiled by tauri-build into
    // `resource.lib` inside OUT_DIR; link the same resource into test
    // binaries so they carry the manifest too.
    if cfg!(target_os = "windows") && env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc") {
        let out_dir = env::var("OUT_DIR").expect("OUT_DIR is not set");
        // Some CMake invocations (e.g. the cli build) can drop a stub
        // `msvcrt.lib` (only a .drectve section) into OUT_DIR. If it ends up
        // on the linker search path it shadows the real CRT and breaks every
        // link with LNK2001 memcpy. Remove it defensively.
        let stray_msvcrt = std::path::Path::new(&out_dir).join("msvcrt.lib");
        if stray_msvcrt.exists() {
            let _ = std::fs::remove_file(&stray_msvcrt);
        }
        let resource = std::path::Path::new(&out_dir).join("resource.lib");
        if resource.exists() {
            // `rustc-link-arg-tests` covers integration-test binaries; the
            // lib unit-test harness (`ame_lib-<hash>.exe`) links the resource
            // itself via the `#[cfg(test)] #[link]` directive in lib.rs.
            println!("cargo:rustc-link-arg-tests={}", resource.display());
            println!("cargo:rustc-link-search=native={}", out_dir);
        } else {
            println!("cargo:warning=resource.lib not found in OUT_DIR; test binaries may lack the Common Controls v6 manifest");
        }
    }

    // Build and link the PP-OCR C++ FFI static library (always included).
    // Requires Visual Studio + CMake; a failure aborts the build rather than
    // producing a binary without OCR support.
    build_ppocr();

    // Build the JBeijing/DrEye helper CLIs (32-bit, bundled under
    // build/static/native/bin). A failure aborts the build.
    #[cfg(target_os = "windows")]
    build_cli();

    // Download runtime assets (Textractor, PP-OCR models) into build/static.
    if let Err(e) = download_runtime_deps() {
        // Hard-fail: the app would silently lack Textractor/PP-OCR at runtime.
        panic!("failed to download runtime dependencies: {e}");
    }
}

/// Download runtime assets into `<project>/build/static`.
///
/// The Rust backend consumes these at runtime via `paths::static_dir`:
/// TextractorCLI/texthook.dll for the Textractor extractor and ncnn models
/// for the PP-OCR engine. Downloads are idempotent (skipped when the files
/// already exist). A failure aborts the build so the app never runs with
/// missing runtime files.
fn download_runtime_deps() -> Result<(), String> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let static_dir = Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .join("build/static");
    let cache_dir = Path::new(&manifest_dir).join("target/runtime-deps");

    let textractor_files = [
        "textractor/x86/TextractorCLI.exe",
        "textractor/x86/texthook.dll",
        "textractor/x64/TextractorCLI.exe",
        "textractor/x64/texthook.dll",
    ];
    let ppocr_files = [
        "ppocr/PP-OCRv5_mobile_det.fp16.ncnn.param",
        "ppocr/PP-OCRv5_mobile_det.fp16.ncnn.bin",
        "ppocr/PP-OCRv5_mobile_rec.fp16.ncnn.param",
        "ppocr/PP-OCRv5_mobile_rec.fp16.ncnn.bin",
        "ppocr/PP-OCRv5_server_det.fp32.ncnn.param",
        "ppocr/PP-OCRv5_server_det.fp32.ncnn.bin",
        "ppocr/PP-OCRv5_server_rec.fp32.ncnn.param",
        "ppocr/PP-OCRv5_server_rec.fp32.ncnn.bin",
    ];

    if !all_exist(&static_dir, &textractor_files) {
        download_textractor(&static_dir, &cache_dir)?;
    }
    if !all_exist(&static_dir, &ppocr_files) {
        download_ppocr(&static_dir)?;
    }
    Ok(())
}

fn all_exist(base: &Path, files: &[&str]) -> bool {
    files.iter().all(|f| base.join(f).exists())
}

fn download_file(url: &str, dst: &Path) -> Result<(), String> {
    if dst.exists() {
        return Ok(());
    }
    // Info-level (shown only with `cargo build -v`).
    println!("downloading {url}");
    let result = (|| -> Result<(), String> {
        let resp = ureq::get(url).call().map_err(|e| e.to_string())?;
        let mut reader = resp.into_reader();
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        let mut file = std::fs::File::create(dst).map_err(|e| e.to_string())?;
        std::io::copy(&mut reader, &mut file).map_err(|e| e.to_string())?;
        Ok(())
    })();
    if result.is_err() {
        // Remove the partial file so the next build retries from scratch.
        let _ = std::fs::remove_file(dst);
    }
    result
}

fn download_textractor(static_dir: &Path, cache_dir: &Path) -> Result<(), String> {
    std::fs::create_dir_all(cache_dir).map_err(|e| e.to_string())?;
    let zip_path = cache_dir.join("Textractor-5.2.0-Zip-Version-English-Only.zip");
    let url = "https://github.com/Artikash/Textractor/releases/download/v5.2.0/Textractor-5.2.0-Zip-Version-English-Only.zip";
    if !zip_path.exists() {
        download_file(url, &zip_path)?;
    }

    let wanted = [
        (
            "Textractor/x86/TextractorCLI.exe",
            "textractor/x86/TextractorCLI.exe",
        ),
        ("Textractor/x86/texthook.dll", "textractor/x86/texthook.dll"),
        (
            "Textractor/x64/TextractorCLI.exe",
            "textractor/x64/TextractorCLI.exe",
        ),
        ("Textractor/x64/texthook.dll", "textractor/x64/texthook.dll"),
    ];
    let result = (|| -> Result<(), String> {
        let archive = std::fs::File::open(&zip_path).map_err(|e| e.to_string())?;
        let mut zip = zip::ZipArchive::new(archive).map_err(|e| e.to_string())?;
        for (entry_name, dst_rel) in wanted {
            let dst = static_dir.join(dst_rel);
            if dst.exists() {
                continue;
            }
            let mut entry = zip
                .by_name(entry_name)
                .map_err(|e| format!("zip entry {entry_name}: {e}"))?;
            if let Some(parent) = dst.parent() {
                std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
            }
            let mut file = std::fs::File::create(&dst).map_err(|e| e.to_string())?;
            std::io::copy(&mut entry, &mut file).map_err(|e| e.to_string())?;
        }
        download_file(
            "https://github.com/Artikash/Textractor/raw/master/LICENSE",
            &static_dir.join("textractor/LICENSE.Textractor.txt"),
        )
    })();
    if result.is_err() {
        // Drop the cached zip so a corrupt/partial download is retried.
        let _ = std::fs::remove_file(&zip_path);
    }
    result
}

fn download_ppocr(static_dir: &Path) -> Result<(), String> {
    const BASE: &str = "https://github.com/nzh63/ppocr2ncnn/releases/download/20250705";
    for model in [
        "PP-OCRv5_mobile_det.fp16.ncnn.param",
        "PP-OCRv5_mobile_det.fp16.ncnn.bin",
        "PP-OCRv5_mobile_rec.fp16.ncnn.param",
        "PP-OCRv5_mobile_rec.fp16.ncnn.bin",
        "PP-OCRv5_server_det.fp32.ncnn.param",
        "PP-OCRv5_server_det.fp32.ncnn.bin",
        "PP-OCRv5_server_rec.fp32.ncnn.param",
        "PP-OCRv5_server_rec.fp32.ncnn.bin",
    ] {
        download_file(
            &format!("{BASE}/{model}"),
            &static_dir.join("ppocr").join(model),
        )?;
    }
    download_file(
        "https://github.com/PaddlePaddle/PaddleOCR/raw/refs/tags/v3.1.0/LICENSE",
        &static_dir.join("ppocr/LICENSE.ppocr.txt"),
    )?;
    Ok(())
}

#[cfg(target_os = "windows")]
fn build_ppocr() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let ppocr_dir = std::path::Path::new(&manifest_dir).join("native/ppocr-ffi");
    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".into());
    let config_dir = if profile == "release" {
        "Release"
    } else {
        "Debug"
    };
    // Cargo's target dir: `CARGO_TARGET_DIR` when customized, otherwise
    // `<manifest_dir>/target` (NOT the repo root).
    let target_dir = env::var("CARGO_TARGET_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| std::path::Path::new(&manifest_dir).join("target"));

    // Native sources are tracked so Cargo only re-runs this script when one
    // of them actually changes (otherwise `yarn dev` re-enters build.rs on
    // every invocation).
    let sources = walk_files(&ppocr_dir);
    track_files(&ppocr_dir);

    // The DLL is also distributed under build/static/native/bin (bundled into
    // packaged apps). When it already exists and is newer than every source
    // file, reuse it instead of re-running CMake — mirrors the old
    // `yarn build:native` incremental behavior.
    let static_bin = std::path::Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .join("build/static/native/bin");
    let canonical = static_bin.join("ppocr_ffi.dll");
    let target_copies = [
        target_dir.join(&profile).join("ppocr_ffi.dll"),
        target_dir.join(&profile).join("deps").join("ppocr_ffi.dll"),
    ];

    if !sources.is_empty() && artifacts_fresh(&sources, std::slice::from_ref(&canonical)) {
        // Cache hit: reuse the already-built DLL; just make sure the copies
        // next to the app/test binaries are still in place.
        for dest in target_copies {
            if let Some(parent) = dest.parent() {
                std::fs::create_dir_all(parent)
                    .unwrap_or_else(|e| panic!("failed to create {}: {e}", parent.display()));
            }
            if !dest.exists() {
                std::fs::copy(&canonical, &dest).unwrap_or_else(|e| {
                    panic!(
                        "failed to copy cached ppocr_ffi.dll to {}: {e}",
                        dest.display()
                    )
                });
            }
        }
        println!("using cached ppocr_ffi.dll (PP-OCR engine)");
        return;
    }

    let dst = cmake::Config::new(&ppocr_dir)
        .define("CMAKE_INSTALL_PREFIX", "")
        .build_target("ppocr_ffi")
        .build();

    // The DLL bundles ncnn + opencv; the Rust side loads it at runtime.
    let dll = dst.join("build").join(config_dir).join("ppocr_ffi.dll");
    if !dll.exists() {
        panic!(
            "ppocr_ffi.dll not found after CMake build: {}",
            dll.display()
        );
    }

    // Distribute the DLL next to the app binary (dev), next to the test
    // binaries, and into the bundled resources (packaged apps).
    let mut dests = vec![
        target_dir.join(&profile),
        target_dir.join(&profile).join("deps"),
        static_bin,
    ];
    dests.dedup();
    for dest in dests {
        std::fs::create_dir_all(&dest)
            .unwrap_or_else(|e| panic!("failed to create {}: {e}", dest.display()));
        std::fs::copy(&dll, dest.join("ppocr_ffi.dll"))
            .unwrap_or_else(|e| panic!("failed to copy ppocr_ffi.dll to {}: {e}", dest.display()));
    }
    // Info-level (shown only with `cargo build -v`).
    println!("built ppocr_ffi.dll (PP-OCR engine)");
}

#[cfg(not(target_os = "windows"))]
fn build_ppocr() {
    // PP-OCR native capture is Windows-only.
}

#[cfg(target_os = "windows")]
fn build_cli() {
    use std::process::Command;

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let cli_dir = std::path::Path::new(&manifest_dir).join("native/cli");
    // Dev layout: <project>/build/static/native/bin (packaged via
    // tauri.conf.json resources `../build/static/**/*` → `static/`).
    let bin_dir = std::path::Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .join("build/static/native/bin");
    let build_dir = std::path::Path::new(&manifest_dir).join("target/cli-build");

    // Same caching scheme as build_ppocr: skip CMake entirely when the CLIs
    // already exist and are newer than the sources.
    let sources = walk_files(&cli_dir);
    track_files(&cli_dir);
    let artifacts = [
        bin_dir.join("JBeijingCli.exe"),
        bin_dir.join("DrEyeCli.exe"),
    ];

    if !sources.is_empty() && artifacts_fresh(&sources, &artifacts) {
        println!("using cached JBeijingCli/DrEyeCli");
        return;
    }

    let build = || -> Result<(), String> {
        std::fs::create_dir_all(&build_dir).map_err(|e| e.to_string())?;

        let configure = Command::new("cmake")
            .args(["-G", "Visual Studio 17 2022", "-A", "Win32", "-S"])
            .arg(&cli_dir)
            .arg("-B")
            .arg(&build_dir)
            .status()
            .map_err(|e| format!("cmake configure failed: {e}"))?;
        if !configure.success() {
            return Err("cmake configure exited non-zero".into());
        }

        let compile = Command::new("cmake")
            .args(["--build"])
            .arg(&build_dir)
            .args(["--config", "Release", "--parallel"])
            .status()
            .map_err(|e| format!("cmake build failed: {e}"))?;
        if !compile.success() {
            return Err("cmake build exited non-zero".into());
        }

        std::fs::create_dir_all(&bin_dir).map_err(|e| e.to_string())?;
        for target in ["JBeijingCli.exe", "DrEyeCli.exe"] {
            let src = build_dir.join("Release").join(target);
            if !src.exists() {
                return Err(format!("{target} not found after CMake build"));
            }
            std::fs::copy(&src, bin_dir.join(target)).map_err(|e| e.to_string())?;
        }
        Ok(())
    };

    if let Err(e) = build() {
        panic!("failed to build JBeijing/DrEye CLIs: {e}");
    }
    // Info-level (shown only with `cargo build -v`).
    println!("built JBeijingCli/DrEyeCli into {}", bin_dir.display());
}

/// Recursively collect files under `dir` (used for freshness checks).
fn walk_files(dir: &Path) -> Vec<std::path::PathBuf> {
    let mut files = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                files.extend(walk_files(&path));
            } else {
                files.push(path);
            }
        }
    }
    files
}

/// Emit `cargo:rerun-if-changed` for every native source file so Cargo does
/// not re-run this build script unless the C++ sources actually change.
fn track_files(dir: &Path) {
    for file in walk_files(dir) {
        println!("cargo:rerun-if-changed={}", file.display());
    }
}

/// True when every artifact exists and is at least as new as the newest source.
fn artifacts_fresh(sources: &[std::path::PathBuf], artifacts: &[std::path::PathBuf]) -> bool {
    let newest = sources
        .iter()
        .filter_map(|f| std::fs::metadata(f).ok())
        .filter_map(|m| m.modified().ok())
        .max();
    let Some(newest) = newest else {
        return artifacts.iter().all(|a| a.exists());
    };
    artifacts.iter().all(|a| {
        std::fs::metadata(a)
            .ok()
            .and_then(|m| m.modified().ok())
            .map(|t| t >= newest)
            .unwrap_or(false)
    })
}
