//! Schema system — replaces `src/main/schema/index.ts`.
//!
//! Generates JSON Schema from Rust types for the frontend options editor.
//! Uses `schemars` for automatic schema derivation.

#![allow(dead_code)]

use serde_json::{json, Map, Value};

/// Derive macro that generates options metadata from an options struct
/// (schema via `schemars`, description from `#[ame(...)]` field attributes).
pub use ame_macros::AmeOptions;

/// Re-export schemars for provider implementations.
pub use schemars::{schema_for, JsonSchema};

/// Implemented by options structs deriving `#[derive(AmeOptions)]`.
///
/// `schema()` is generated from the type via [`options_schema`]; `description()`
/// is generated by the derive from the `#[ame(...)]` field attributes, so
/// description keys always match real struct fields (typos are compile errors).
pub trait AmeOptions: JsonSchema + serde::Serialize + Default {
    fn schema() -> Value {
        options_schema::<Self>()
    }

    fn description() -> Value;
}

/// Convert a `schemars` schema into a plain JSON value for IPC transfer.
pub fn to_json_schema<T: JsonSchema>() -> Value {
    let schema = schema_for!(T);
    serde_json::to_value(schema).unwrap_or(Value::Null)
}

/// Generate the options schema for a provider/manager/extractor options type.
///
/// `schemars` output is post-processed so it matches the frontend editor's
/// expectations (and the original JS `toJSONSchema` output):
/// 1. `$ref: #/definitions/X` property schemas are inlined — the editor reads
///    `enum`/`type` directly on the property.
/// 2. `properties` are reordered to the struct's field declaration order
///    (taken from the serialized `T::default()`), because schemars sorts them
///    alphabetically (BTreeMap).
/// 3. `default` values are merged recursively from `T::default()`.
/// 4. `integer` is normalized to `number` (JS numbers).
/// 5. booleans get `"enum": [true, false]` so the editor renders a select.
pub fn options_schema<T: JsonSchema + serde::Serialize + Default>() -> Value {
    let mut schema = to_json_schema::<T>();
    let defaults = serde_json::to_value(T::default()).unwrap_or(Value::Null);

    inline_definitions(&mut schema);
    flatten_all_of(&mut schema);
    reorder_and_merge(&mut schema, &defaults);
    normalize(&mut schema);
    schema
}

/// Replace `$ref: #/definitions/<name>` nodes with the referenced definition,
/// recursively (definitions may reference other definitions).
fn inline_definitions(schema: &mut Value) {
    let definitions = schema.get("definitions").cloned();
    if let Some(definitions) = definitions {
        inline_into(schema, &definitions);
        if let Value::Object(map) = schema {
            map.remove("definitions");
        }
    }
}

fn inline_into(node: &mut Value, definitions: &Value) {
    match node {
        Value::Object(map) => {
            if let Some(reference) = map.get("$ref").and_then(|r| r.as_str()) {
                let name = reference.trim_start_matches("#/definitions/");
                if let Some(def) = definitions.get(name) {
                    let mut replacement = def.clone();
                    inline_into(&mut replacement, definitions);
                    *node = replacement;
                    return;
                }
            }
            for value in map.values_mut() {
                inline_into(value, definitions);
            }
        }
        Value::Array(items) => {
            for item in items.iter_mut() {
                inline_into(item, definitions);
            }
        }
        _ => {}
    }
}

/// `schemars` wraps enums (and other schemas carrying metadata) in
/// `"allOf": [...]`. The frontend editor reads `enum`/`type` directly on the
/// property, so merge the `allOf` members into the node.
fn flatten_all_of(node: &mut Value) {
    match node {
        Value::Object(map) => {
            if let Some(Value::Array(members)) = map.remove("allOf") {
                for member in members {
                    if let Value::Object(member_map) = member {
                        for (key, value) in member_map {
                            map.entry(key).or_insert(value);
                        }
                    }
                }
            }
            for value in map.values_mut() {
                flatten_all_of(value);
            }
        }
        Value::Array(items) => {
            for item in items.iter_mut() {
                flatten_all_of(item);
            }
        }
        _ => {}
    }
}

/// Reorder object `properties` to match the default value's key order (struct
/// field declaration order) and merge `default` values recursively.
fn reorder_and_merge(schema: &mut Value, defaults: &Value) {
    if let (Some(smap), Some(dmap)) = (schema.as_object_mut(), defaults.as_object()) {
        if let Some(props) = smap.get_mut("properties").and_then(|p| p.as_object_mut()) {
            let mut ordered: Map<String, Value> = Map::new();
            for (key, dval) in dmap {
                if let Some(prop) = props.remove(key) {
                    let mut prop = prop;
                    reorder_and_merge(&mut prop, dval);
                    ordered.insert(key.clone(), prop);
                }
            }
            for (key, val) in std::mem::take(props) {
                ordered.insert(key, val);
            }
            *props = ordered;
        }
    }
    if let Value::Object(smap) = schema {
        // `T::default()` is authoritative — schemars' reflection of
        // `#[serde(default)]` (e.g. `false` for bools) may differ.
        smap.insert("default".into(), defaults.clone());
    }
}

/// Normalize types for the frontend: `integer` → `number`, booleans get an
/// `enum` so they render as selects.
fn normalize(node: &mut Value) {
    match node {
        Value::Object(map) => {
            if map.get("type").and_then(|t| t.as_str()) == Some("integer") {
                map.insert("type".into(), Value::String("number".into()));
            }
            if map.get("type").and_then(|t| t.as_str()) == Some("boolean") {
                map.insert("enum".into(), json!([true, false]));
            }
            for value in map.values_mut() {
                normalize(value);
            }
        }
        Value::Array(items) => {
            for item in items.iter_mut() {
                normalize(item);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::{Deserialize, Serialize};
    use serde_json::json;

    #[derive(JsonSchema, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct UserOptions {
        name: String,
        age: u32,
        active: bool,
    }

    #[derive(JsonSchema, Serialize, Deserialize)]
    struct TaggedOptions {
        theme: Theme,
        tags: Vec<String>,
        nullable: Option<String>,
    }

    #[derive(JsonSchema, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    enum Theme {
        Light,
        Dark,
    }

    #[test]
    fn object_schema_has_type_properties_and_required() {
        let schema = to_json_schema::<UserOptions>();
        assert_eq!(schema["type"], json!("object"));
        assert!(schema["properties"].is_object());
        assert!(schema["properties"]["name"].is_object());
        assert_eq!(schema["properties"]["name"]["type"], json!("string"));
        assert_eq!(schema["properties"]["age"]["type"], json!("integer"));
        assert_eq!(schema["properties"]["active"]["type"], json!("boolean"));

        let required = schema["required"].as_array().unwrap();
        assert!(required.contains(&json!("name")));
        assert!(required.contains(&json!("age")));
        assert!(required.contains(&json!("active")));
    }

    #[test]
    fn enum_schema_has_enum_values() {
        let schema = to_json_schema::<TaggedOptions>();
        // schemars emits named enums as a $ref into `definitions`.
        let theme = &schema["definitions"]["Theme"];
        assert_eq!(theme["type"], json!("string"));
        assert!(theme["enum"].is_array());
        let values: Vec<&str> = theme["enum"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|v| v.as_str())
            .collect();
        assert_eq!(values, vec!["light", "dark"]);
        assert_eq!(
            schema["properties"]["theme"]["$ref"],
            json!("#/definitions/Theme")
        );
    }

    #[test]
    fn array_schema_has_items() {
        let schema = to_json_schema::<TaggedOptions>();
        let tags = &schema["properties"]["tags"];
        assert_eq!(tags["type"], json!("array"));
        assert!(tags["items"].is_object());
    }

    #[test]
    fn nullable_field_is_not_required() {
        let schema = to_json_schema::<TaggedOptions>();
        let required = schema["required"].as_array().unwrap();
        assert!(required.contains(&json!("theme")));
        assert!(required.contains(&json!("tags")));
        assert!(!required.contains(&json!("nullable")));
        // Option<T> may render as a type array or an anyOf — either way it must
        // include null.
        let nullable = &schema["properties"]["nullable"];
        let is_nullable = nullable
            .get("type")
            .and_then(|t| t.as_array())
            .is_some_and(|a| a.iter().any(|x| x == "null"))
            || nullable
                .get("anyOf")
                .and_then(|a| a.as_array())
                .is_some_and(|a| a.iter().any(|x| x["type"] == "null"));
        assert!(is_nullable, "nullable field must accept null: {nullable}");
    }

    #[derive(JsonSchema, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct RealOptions {
        #[serde(default = "default_enable")]
        enable: bool,
        model: Model,
        #[serde(default)]
        count: u64,
        #[serde(default)]
        secret: Option<String>,
    }

    impl Default for RealOptions {
        fn default() -> Self {
            Self {
                enable: default_enable(),
                model: Model::default(),
                count: 0,
                secret: None,
            }
        }
    }

    fn default_enable() -> bool {
        true
    }

    #[derive(JsonSchema, Serialize, Deserialize, Clone, Copy, Default)]
    enum Model {
        #[default]
        #[serde(rename = "server.fp32")]
        Server,
        #[serde(rename = "mobile.fp16")]
        Mobile,
    }

    #[test]
    fn options_schema_inlines_enums_and_preserves_order_and_defaults() {
        let schema = options_schema::<RealOptions>();
        let props = schema["properties"].as_object().unwrap();

        // Field order must match the struct declaration (enable, model, count, secret).
        let keys: Vec<&String> = props.keys().collect();
        assert_eq!(keys, vec!["enable", "model", "count", "secret"]);

        // Enums are inlined with their renamed values.
        assert_eq!(props["model"]["type"], json!("string"));
        let values: Vec<&str> = props["model"]["enum"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|v| v.as_str())
            .collect();
        assert_eq!(values, vec!["server.fp32", "mobile.fp16"]);

        // Booleans get an enum + default from T::default().
        assert_eq!(props["enable"]["enum"], json!([true, false]));
        assert_eq!(props["enable"]["default"], json!(true));

        // integer is normalized to number; defaults merged; Option gets null.
        assert_eq!(props["count"]["type"], json!("number"));
        assert_eq!(props["count"]["default"], json!(0));
        assert_eq!(props["secret"]["default"], Value::Null);
        assert_eq!(schema["default"]["enable"], json!(true));
    }

    #[derive(JsonSchema, Serialize, Deserialize, Default, AmeOptions)]
    #[serde(rename_all = "camelCase")]
    struct ReproOptions {
        #[ame(desc = "启用")]
        enable: bool,
    }

    #[test]
    fn derive_repro_compiles() {
        let schema = <ReproOptions as AmeOptions>::schema();
        assert_eq!(schema["properties"]["enable"]["enum"], json!([true, false]));
        assert_eq!(
            <ReproOptions as AmeOptions>::description(),
            json!({ "enable": "启用" })
        );
    }

    #[test]
    fn generated_schema_matches_frontend_contract() {
        let schema = <crate::providers::ocr::ppocr::PpOcrOptions as AmeOptions>::schema();
        let props = schema["properties"].as_object().unwrap();

        // Field order follows the struct declaration.
        let keys: Vec<&String> = props.keys().collect();
        assert_eq!(keys, vec!["enable", "model", "device", "textDirection"]);

        // Enums are inline (no allOf/$ref) so the editor renders a select.
        assert!(props["model"].get("allOf").is_none(), "no allOf: {props:?}");
        assert!(props["model"].get("$ref").is_none());
        let models: Vec<&str> = props["model"]["enum"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|v| v.as_str())
            .collect();
        assert_eq!(models, vec!["server.fp32", "mobile.fp16"]);

        // Defaults come from T::default() (enable is true).
        assert_eq!(props["enable"]["default"], json!(true));
        assert_eq!(props["model"]["default"], json!("server.fp32"));
    }
}
