name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        arch: [x64, ia32]

    env:
      npm_config_arch: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - run: yarn type-check

      - run: yarn download:dep

      - run: yarn test
        env:
          DEBUG: ame:*
          DEBUG_COLORS: '1'

      - run: yarn build --arch=${{ matrix.arch }} --publish=never

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.arch }}
          path: build/*.exe
