name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 20.x (yarn cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - run: yarn type-check

      - run: cargo fmt --manifest-path src-tauri/Cargo.toml --check

      - run: cargo clippy --manifest-path src-tauri/Cargo.toml --all-targets -- -D warnings

      - run: yarn test

      - run: yarn e2e

      - run: yarn build
