name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn tauri:build

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: src-tauri/target/release/bundle/nsis/*.exe

  release:
    runs-on: windows-latest

    needs: build

    if: success()

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        run: npx --yes conventional-changelog-cli@5.0.0 -p angular -o CHANGELOG.md -r 2
      - run: cat CHANGELOG.md

      - uses: actions/download-artifact@v4
        with:
          name: release
          path: release-artifact

      - uses: softprops/action-gh-release@v2
        with:
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: CHANGELOG.md
          files: release-artifact/*
